### ISSUE TITLE
Differences from universal-redux-router to react-router

### ISSUE THREAD

**Issue by felixsanz** [colinmeinke/universal-js#23]
Can you please explain a bit why a custom `universal-redux-router` is made over the typical `react-router` ?

**Comment by colinmeinke** [comment]
Sure. Initially I was having problems getting Redux Router (RR) playing nice with server rendering. I also wasn't such a fan that RR was handling a bunch of state itself. I wanted Redux to be my only source of state.

After reading this article I realised Routing didn't need to be so complicated – https://gist.github.com/HenrikJoreteg/530c1da6a5e0ff9bd9ad so built Universal Redux Router (URR), which essentially just stored the URL in the Redux store.

Since then I _have_ complicated URR a bit, as I wanted it to support running actions automatically when a route changed. I found I was repeatedly pulling state out the URL every time the URL changed and then dispatching actions with that state. I thought it made sense for the router to be the place to handle this.

I have bigger plans for the future of URR - http://www.colinmeinke.com/post/rethinking-routes
